### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ondrejmirtes** [phabelio/phabel#5] opened 2021-09-08 08:58 UTC
When trying to transpile PHPStan's source, I get this error:

```
Syntax error, unexpected ',' on line 390 while parsing /Users/ondrej/Development/phpstan/src/Command/FixerApplication.php!
```

But of course the source code is valid PHP and there's [nothing special on line 390](https://github.com/phpstan/phpstan-src/blob/bfadbdd81ae827ab7f5d76dd929994ff13bbe747/src/Command/FixerApplication.php#L390).

**Comment by danog** [comment] 2021-09-08 13:42
Hmm, this is actually caused by the `await` keyword, which is treated by Phabel as the reserved [`await` keyword for amphp-based coroutines](https://github.com/phabelio/phabel#asyncawait-syntax).  
I'll come up with a workaround, in the meantime aliasing the imported React function as `awaitFunc` should fix the issue.

**Comment by danog** [comment] 2021-09-08 17:37
This is now fixed!

**Comment by danog** [comment] 2021-09-08 17:39
If you need any more help with integrating phabel into phpstan, just open another issue or ping me [@danogentili](https://t.me/danogentili) on Telegram, or drop a letter @ daniil@daniil.it, I'd be more than glad to help! :)

**Closed as completed by danog** 2021-09-08 17:39 UTC

**Comment by ondrejmirtes** [comment] 2021-09-08 17:40
Thank you :) The dream is to have the newest dependencies, develop with PHP 8.0, and be able to transpile for PHP 7.1. Right now I'm transpiling just typed properties in my own code using a simple script: https://github.com/phpstan/phpstan-src/blob/master/bin/transform-source.php And the dependencies are old because they need to be compatible with PHP 7.1.

**Comment by danog** [comment] 2021-09-08 19:10
Phabel is perfect for your usecase: I see you're compiling phpstan as a phar, and releasing that to composer, for that, simply running the run command is enough.

However, phabel can also help you in deps like https://github.com/phpstan/phpdoc-parser, applying any needed transforms directly upon installation, similar to what you do for a few files using vaimo/composer-patches, only a bit more useful :)

**Comment by danog** [comment] 2021-09-08 22:04
I'll make a few PRs to some phpstan repos to begin integration, if that's OK for you :)

**Comment by ondrejmirtes** [comment] 2021-09-09 07:33
As a first step I'd like to see dependencies being updated to at least `^7.4` while keeping the 7.1 compatibility in the PHAR.

You can definitely try to achieve that, the CI build will tell you what's wrong and what's fine :)

Myself I'd like to look into it in a few months, it's more of a procrastination distraction right now as I need to release PHPStan 1.0 and PHP 8.1 support :)

**Comment by ondrejmirtes** [comment] 2021-09-09 07:37
The extra challenge of having `"php": "^8.0"` in composer.json in phpstan-src is that for PHP 7.x, we need to modify `composer.json` to work on PHP 7.x while having the same PHP ^8.0 dependencies installed. That's why I'd like to postpone it.
